// src/services/intentClassifier.js
import dotenv from 'dotenv';
dotenv.config();

const VALID_CATEGORIES = [
    'academic_regulations',
    'accreditation',
    'college_events',
    // 'college_info',
    'department_info',
    'department_info_aids',
    'department_info_aiml',
    'department_info_bsh',
    'department_info_civil',
    'department_info_cse',
    'department_info_ece',
    'department_info_eee',
    'department_info_it',
    'department_info_mech',
    'examination_results',
    'faculty_admin',
    'faculty_aids',
    'faculty_aiml',
    'faculty_bsh',
    'faculty_civil',
    'faculty_cse',
    'faculty_ece',
    'faculty_eee',
    'faculty_hod',
    'faculty_it',
    'faculty_mech',
    'hostel_info',
    'nss_extension_activities',
    'old_question_papers',
    'payments_info',
    'pg_programs_overview',
    'placement_record',
    'ranking',
    'research',
    'resources_labs',
    'resources_library',
    'student_council',
    'student_incentives',
    'student_policy',
    'tech_magazine',
    'Student Club',
      'About GMRIT',
    'Vision_Gmrit',
    'Mission_Gmrit',
    'Achievements',
    'Contact_Gmrit',
    'List_holidays_2025',
    'Hostels',
    'GATE-2024',
    'Sports',



    'Publications_GMRIT_overall',
    'Patents_GMRIT_overall',
    'Gold OA_GMRIT_overall',
    'Bronze OA_GMRIT_overall',
    'Green OA_GMRIT_overall',
    'Journal Articles_GMRIT_overall',
    'Conference / In Proceedings_GMRIT_overall',
    'Books / Chapters_GMRIT_overall',
    'Other_GMRIT_overall',




    'Hierarchiacal_College',


    
    'Mechanical Engineering_ResearchProfile',
    'Electrical and Electronic Engineering_ResearchProfile',
    'Information Technology_ResearchProfile',
    'Civil Engineering_ResearchProfile',
    'AI&MLResearchProfile',
    'BSH Department_ResearchProfile',
    'CSE_ResearchProfile',
    'ECE_ResearchProfile',

    'civil_syllabus_dwnld_AR202123',
    'cse_syllabus_dwnld_AR202123',
    'eee_syllabus_dwnld_AR202123',
    'ece_syllabus_dwnld_AR202123',
    'mech_syllabus_dwnld_AR202123',
    'it_syllabus_dwnld_AR202123',
    'cse_aids_syllabus_dwnld_AR202123',
    'cse_aiml_syllabus_dwnld_AR202123',

    'Student_Council',
    'Student_Clubs',

    'faculty_ongoing_projects',




    'Cognizant_2023',
    'GMR Goup_2023',
    'Happiest Minds_2023',
    'TCS_2023',
    'Hexaware_2023',
    'Nagarro_2023',
'Soprasteria_2023',
'TCS Codevita(Digital-14,Ninja-6)_2023' ,
'Upgrad_2023',
'Inmovidutech_2023',
'Revidd(Inflolabs)_2023',
'Cerium-Systems_2023',
'Sarvani Industries_2023',
'Hetero Drugs_2023',
'Sri Shirdi Sai Electricals_2023',
'ADP_2023',
'Delphi TVS_2023',
'Cognizant (Gen C) 2.0_2023',
'Alphabridge_2023',
'JSW_2023',
'LnT Group_2023',
'Waisl_2023',
'Novisync_2023',
'Rinex Technologies_2023',
'Beumer Group_2023',
'Skillhacc_2023',
'GMR Group Phase II_2023',
'Infosys INFY TQ_2023',
'Brillio_2023',
'Deloitte_2023',
'Tudip Technologies_2023',
'MGH Infra_2023',
'Evolutyz_2023',
'Logikworks_2023',
'ttec_2023',
'ContentQL_2023',
'Cognizant (Gen C Next) 2.0_2023',
'Pennant Technologies_2023',
'Adeptchips_2023',
'Soctronics_2023',
'CSS Corp._2023',
'iLensys_2023',
'Hansa Solutions_2023',
'Infor_2023',
'BSCPL_2023',
'Tech Mahindra_2023',
'Efftronics_2023',
'Vihaan Electix_2023',
'Mindbrink Media_2023',
'Transcon_2023',
'IBM_2023',
'Unistring_2023',
'Medha Servo_2023',
'Unschool_2023',
'IBM Phase II(Code Nack)_2023',
'OSI Digital_2023',
'Mitsogo_2023',
'RDC_2023',
'Hyundai Motors_2023',
'FacePrep_2023',
'Nagarjuna Fertilizers & Chemicals_2023',
'Ramky_2023',
'Virtusa Neural Hack_2023',
'IMEG_2023',
'India Cements_2023',
'Deccan Fine Chemicals_2023',
'Vayu Group_2023',
'Carbon Resources_2023',
'AUS Phase II_2023',
'ByjuS_2023',
'Satven(Satyam Ventures)_2023',
'SmartDV Technologies_2023',
'Amazon - Transport Specialist_2023',
'Aarvee Associates_2023',
'GMR Group_2024',
'Surya Tech Solutions_2024',
'Inmovidu Tech_2024',
'TCS_2024',
'Edustation_2024',
'Accenture_2024',
'LnT_2024',
'MSN Laboratories Pvt. Ltd._2024',
'Tata Consulting Engineers(TCE)_2024',
'Euthissa_2024',
'Ocean Technologies_2024',
'Miracle Software Systems_2024',
'KMV Projects Ltd.,_2024',
'Tech Mahindra_2024',
'Vijay Nirman_2024',
'Meraqui_2024',
'Philips Engineering Services_2024',
'Megawide_2024',
'Sakura Autoparts pvt. Ltd._2024',
'ARF Design Pvt Ltd._2024',
'Ttec_2024',
'Waisl_2024',
'Excel Global Solution_2024',
'BSPCL_2024',
'India Cements_2024',
'Interarchbuilding_2024',
'Shyam Metalics & Energy Limited_2024',
'Protiviti_2024',
'MGH Infrastructures_2024',
'Efftronics_2024',
'Micro Electricals_2024',
'Essen Electrions Systems Pvt. Ltd.,_2024',
'ReNote_2024',
'Tudip_2024',
'Nisum_2024',
'Hexaware_2024',
'Deloitte_2024',
'Sail Software_2024',
'Cognizant Gen C_2024',
'ADP_2024',
'Unschool_2024',
'DFPCL_2024',
'MetaIntrospec_2024',
'Bharat Electronics Ltd.,_2024',
'GMR Innovex_2024',
'Edu-Versity_2024',
'Regami Solutions_2024',
'Laurus Labs_2024',
'Excelmax Technologies Pvt, Ltd.,_2024',
'PalTech_2024',
'Vihaan Electrix_2024',
'Drishya.AI_2024',
'Sarvani Industries_2024',
'Reliance Industries_2024',
'Bosch_2024',
'MosChip Technologies_2024',
'IMEG Corporation_2024',
'Fleming Labaratories Ltd_2024',
'Medha Servo Drives_2024',
'Cognizant_2024',
'RDC Concrete_2024',
'Hyundai Motor India Engineering Pvt Ltd_2024',
'Infinity Learn_2024',
'Argoid_2024',
'E-Greaser_2024',
'Seventh Edge Consulting Services Pvt. Ltd.,_2024',
'VU-DYNAMICS PRIVATE LIMITED_2024',
'Safran_2024',
'SSWITCH Technologies_2024',
'SHAKYA HR SOLUTIONS Pvt Ltd._2024',
'Data Marshall_2024',
'Affosoft_2024',
'Soprasteria_2024',
'GROUPE ADP_2024',
'Infosys_2025',
'GMR Group_2025',
'MEIL_2025',
'Cognizant_2025',
'MRF Tyres_2025',
'LTI Mindtree_2025',
'JSW_2025',
'Arrowsight_2025',
'Modak Analytics_2025',
'Cadsys_2025',
'Interarch Building_2025',
'HCL_2025',
'Deloitte_2025',
'NCC_2025',
'Honor Labs_2025',
'ARF Design_2025',
'HTC Global_2025',
'Rashmi Metalics_2025',
'Polyrub Cooperstandard FTS Pvt Ltd_2025',
'Nisum Technologies_2025',
'India Cements_2025',
'Vijay Nirman_2025',
'LnT_2025',
'Philips_2025',
'GGS Engineering_2025',
'My Home_2025',
'Megawide_2025',
'Coromandel International Ltd_2025',
'Solarsqure_2025',
'Revidd_2025',
'RDC Concrete_2025',
'Organo Eco Habitats Pvt. Ltd.!_2025',
'Magnaquest_2025',
'TCS_2025',
'Delphi TVS_2025',
'PalTech_2025',
'VemTechnologies_2025',
'Veena Energy_2025',
'Milekal_2025',
'Beumer Group_2025',
'ZEN Technologies_2025',
'Efftronics_2025',
'Tata Advance Systems_2025',
'Kalgudi Digital Pvt. Ltd._2025',
'Mufront Technologies_2025',
'Akrivia HCM_2025',
'Alphabridge_2025',
'Tag N Trac India_2025',
'Regami_2025',
'QualityKiosk_2025',
'Polycab_2025',
'Kokban Automation_2025',
'HBL Batteries_2025',
'Moschip_2025',
'Bluesapphire_2025',
'DeltaX_2025',
'Darwinbox_2025',
'Reliance Industries_2025',
'Veda IIT_2025',
'Medha Servo_2025',
'Oracle_2025',
'Technodeal_2025',
'Forty2 Enterprises_2025',
'Aptroid_2025',
'Dhrishya.Ai_2025',
'BrowserStack_2025',
'Possiable Works_2025',
'Techouts_2025',
'Trellix_2025',
'Total_Placements_2025',
'Total_Placements_2024',
'Total_Placements_2023',
'Dr Prasad C L V R S V_research profile',
'Dr Sasikumar Gnanasekaran_research profile',
'Dr M Srinivasa Rao_research profile',
'Dr Puvvada Nagalakshmi Pavani_research profile',
'Dr Santarao Korada_research profile',
'Dr Bade Venkata Suresh_research profile',
'Dr Vijaybabu T R_research profile',
'Dr Chiranjeeva Rao Seela_research profile',
'Dr Ravibabu Sajja_research profile',
'Dr Vykuntarao M_research profile',
'Mr Pavan Nagendra_research profile',
'Dr A. Lakshumu Naidu_research profile',
'Dr SASIDHAR GURUGUBELLI_research profile',
'Dr Yegireddi Shireesha_research profile',
'Dr Siva Prasad Kattela_research profile',
'Dr Bappa Mondal_research profile',
'Mr SUDHAKAR UPPADA_research profile',
'Dr Ch Vinod Babu_research profile',
'Mr Govindarao Nammi_research profile',
'Simhadri Kambala_research profile',
'Dr Prashant Kumar Choudhary_research profile',
'Dr Gorti Janardhan_research profile',
'Dr Shanmukhasundaram V R_research profile',
'Dr Velamala Rambabu_research profile',
    'Dr G Chandra Sekhar_research profile',
'Dr T S Kishore_research profile',
'Dr Rajesh Kumar Patnaik_research profile',
'Dr Ayyarao Tummala S L V_research profile',
'Dr Kumar L V S_research profile',
'Dr Rambabu M_research profile',
'Dr N. V. A. Ravikumar_research profile',
'Mr Ravi Kumar Jalli_research profile',
'Dr Polamarasetty Praveen Kumar_research profile',
'Dr Ramakrishna Raghutu_research profile',
'Dr Guntuku Indira Kishore_research profile',
'Dr Hemanthakumar Chappa_research profile',
'Mr Vijaya Krishna Rayi_research profile',
'Dr Upendra Kumar P_research profile',
'Dr Vasupalli Manoj_research profile',
'Dr Venkatesh Mudadla_research profile',
'Dr M Vinay Kumar_research profile',
'Mr Damala Rajesh Babu_research profile',
'Dr Ajit Kumar Rout_research profile',
'Dr P AnnanNaidu_research profile',
'Dr Vaddadi Vasudha Rani_research profile',
'Dr Satish Muppidi_research profile',
'Dr Jayasri Kotti_research profile',
'Dr Stalin Babu Gedela_research profile',
'Ms Padmaja B_research profile',
'Dr Daniya T_research profile',
'Mrs Santoshi Kancherla_research profile',
'Dr Aravind Karrothu_research profile',
'Ms Pooja Panapana_research profile',
'Mrs Swathi Lenka_research profile',
'Dr Girish Jammigumpula_research profile',
'Dr GANESH PRABHU GANAPATHY_research profile',
'Dr Sridhar Jayaprakash_research profile',
'Dr Vivek S_research profile',
'Dr NAGIREDDY NAGESWARA REDDY_research profile',
'Mr Bimalendu Dash_research profile',
'Mr Ramu Penki_research profile',
'Mr P R V S Priyatham Batchu_research profile',
'Dr Pandi Mani_research profile',
'Mr Athibaranan S_research profile',
'Ms Priya V_research profile',
'Dr Abu Rashid_research profile',
'Ms Jyotsna Mangaraju_research profile',
'Dr Priyanka Atmakuri_research profile',
'Mrs Padmavathi Pragada_research profile',
'Mr Harikrishna Marrapu_research profile',
'Bharathi chowdada_research profile',
'Mr Suragali chanti_research profile',
'Dr Surya Narayan Dash_research profile',
'Dr Chaduvula Ramya_research profile',
'Dr Venkataramana Attada_research profile',
'Dr Venkataramana Attada_research profile',
'Dr Sowjanya Dangety_research profile',
'Mr Devadi Ganesh_research profile',
'Mr Suraj Soren_research profile',
'Ms Binodini Kar_research profile',
'Mrs Sakunthala Kovelakonda_research profile',
'Mrs Nirosha Gorisetty_research profile',
'Mrs Tanna Anusha_research profile',
'Lavanya Molleti_research profile',
'Mrs Lavanya G_research profile',
'Ms Tandra Sowmya_research profile',
'Ms Kundhi Kiranmai_research profile',
'Mr Suneel Gollapalli_research profile',
'Mrs Meesala Sravani_research profile',
'Mr Srinuvasarao Desetti_research profile',
'Mr Gangu Dharmaraju_research profile',
'Ms Bangaru Krishnaveni Kotni_research profile',
'Mr S Vinodkumar_research profile',
'Ms Santhoshini Sahu_research profile',
'Mrs Vineela Allada_research profile',
'Mrs Ashapu Bhavani_research profile',
'Ms Nagamani Yanda_research profile',
'Dr Srividya Kotagiri_research profile',
'Dr Ch Sekhar_research profile',
'Dr Srinadh Vemireddi_research profile',
'Dr SatishKumar Patnala_research profile',
'Dr Sreejyothsna Ankam_research profile',
'Dr T Daniya_research profile',
'Dr Lakshmidevi Nydhana_research profile',
'Ms Nidrabingi Krishna Veni_research profile',
'Mrs Prasanna Simhadati_research profile',
'Smt Madhavi Perla_research profile',
'Ms Sowmya T_research profile',
'Mrs S Prasanna_research profile',
'Ms Sucheta Panda_research profile',
'Mrs Madhavi Perla_research profile',
'Dr Jagan Naveen V_research profile',
'Dr Ravi Shankar Saxena_research profile',
'Dr Jami Venkata Suman_research profile',
'Dr DIVAKAR TVS_research profile',
'Dr A Sivasangari_research profile',
'Dr Babji Prasad Chapa_research profile',
'Dr Geetamma Tummalapalli_research profile',
'Dr Koduri Sreelakshmi_research profile',
'Dr Vasudeva Bevara_research profile',
'Dr Anilkumar Tirunagari_research profile',
'Dr Anil Kumar B_research profile',
'Dr NAGANDLA PRASAD_research profile',
'Dr Guntu Nooka Raju_research profile',
'Mr B.M.S. Sreenivasa Rao_research profile',
'Mr Murali Nattala_research profile',
'Dr JAMI VENKATA SUMAN_research profile',
'Dr Anantha Rao Gondu_research profile',
'Dr Suresh D_research profile',
'Mrs Revathi P_research profile',
'Mr Murali Pillala_research profile',
'Mr Kalyanchakravarthi Pulletikurti_research profile',
'Dr Mohd Rizwan Uddin Shaikh_research profile',
'Mrs Shanmathi Shanmuganathan_research profile',
'Dr RAVI KUMAR PALLA_research profile',
'Dr NADIKATLA CHANDRASEKHAR_research profile',
'Dr GBSR Naidu_research profile',
'Dr Mittapalli Venkata Nageswara Rao_research profile',

'GMRIT_ResearchProfiles_Overall',


'Computer Science and Engineering_MTECH',
'Power and Industrial Drives_MTECH',
'Transportation Engineering_MTECH',
'VLSI and Embedded Systems Design_MTECH',
'Thermal Engineering_MTECH',


"professional_body",
// 'Professional Bodies_SAE',
// 'Professional Bodies_CSI',
// 'Professional Bodies_IICHE',
// 'Professional Bodies_ACM',
// 'Professional Bodies_ISTE',
// 'Professional Bodies_IETE',
// 'Professional Bodies_IEEE',


'Student Club_FilimClub',
'Student Club_PhotographyClub',
'Student Club_CodingClub',
'Student Club_MathClub',
'Student Club_LiteraryClub',
'Student Club_ProjectClub',
'Student Club_WomenEmpormentClub',
'Student Club_CivilServiceClub',
'Student Club_MusicClub',
'Student Club_DanceClub',
'Student Club_RoboticsClub',
'Student Club_GoogleDeveloperClub',
'Student Club_StemClub',
'Student Club_sectorClub',
'Student Club_GreenEcoClub',
'Student Club_HAMClub',
'Student Club_HobbyClub',
'Student Club_UnnatBharatAbhiyanClub',


'Student Council_President',
'Student Council_VicePresident',
'Student Council_VicePresident',
'Student Council_GeneralSecretary',
'Student Council_GeneralSecretary',
'Student Council_JointSecretary',
'Student Council_JointSecretary',
'Student Council_JointSecretary',
'Student Council_JointSecretary',
'Student Council_JointSecretary',
'Student Council_JointSecretary',
'Student Council_JointSecretary',
'Student Council_JointSecretary',
'Student Council_JointSecretary',

'Total_Placements_2025',
'Total_Placements_2024',
'Total_Placements_2023',

'btech&mtechdepartment'





    



    



    
];

/**
 * Classifies a user's query into one of the predefined categories using an LLM.
 * @param {string} query - The user's query.
 * @returns {Promise<string>} The classified category or 'none' if no category fits.
 */
export async function classifyQueryWithLLM(query) {
    const chatHistory = [{
        role: 'user',
        parts: [{
            text: `Classify the following user query into one of the following categories: ${VALID_CATEGORIES.join(', ')} If none of the categories fit, respond with 'none'.\n\nUser Query: "${query}"
            Map the user requests into the appropriate categories. Mostly there will be a clear mapping based on the content of the query. for example asking about principal don't go for college_info since every info is college info ..principal it is designation can be found in admin faculties so be careful.`
        }]
    }];

    const payload = {
        contents: chatHistory,
        generationConfig: {
            responseMimeType: 'application/json',
            responseSchema: {
                type: 'OBJECT',
                properties: {
                    "category": { "type": "STRING" }
                }
            }
        }
    };
    
    const apiKey = process.env.GEMINI_API_KEY;
    const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-preview-05-20:generateContent?key=${apiKey}`;
    
    try {
        const response = await fetch(apiUrl, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
        });

        const result = await response.json();
        const jsonString = result?.candidates?.[0]?.content?.parts?.[0]?.text;

        if (jsonString) {
            const parsedJson = JSON.parse(jsonString);
            const classifiedCategory = parsedJson.category;

            if (VALID_CATEGORIES.includes(classifiedCategory)) {
                return classifiedCategory;
            }
        }
    } catch (error) {
        console.error('Error classifying query with LLM:', error);
    }

    return 'none';
}
